# Generated by Django 5.0.3 on 2024-03-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
